services:
  webapp:
    build: .
    env_file:
      - ".env"
    command: sh -c "cd backend && uvicorn api:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload"
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    working_dir: /app
    volumes:
      - ./:/app
      - DB_Data:/var/lib/db_data
volumes:
  DB_Data: