services:
  webapp:
    build: .
    env_file:
      - ".env"
    command: sh -c "/usr/local/bin/supervisord"
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    working_dir: /app
    volumes:
      - ./:/app
      - DB_Data:/var/lib/db_data
volumes:
  DB_Data: